apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-admission-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp
subjects:
- kind: ServiceAccount
  name: default
  namespace: ingress-admission
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-admission
  namespace: ingress-admission
  labels:
    name: ingress-admission
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    name: ingress-admission
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ingress-admission
  namespace: ingress-admission
  labels:
    name: ingress-admission
spec:
  replicas: 2
  template:
    metadata:
      name: ingress-admission 
      labels:
        name: ingress-admission
    spec:
      containers:
        - name: webhook
          image: ingress-admission:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: 50Mi
              cpu: 300m
            requests:
              memory: 50Mi
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: ingress-admission-certs
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: ingress-admission
webhooks:
  - name: ingress-admission.tools.wmflabs.org
    clientConfig:
      service:
        name: ingress-admission
        namespace: ingress-admission
        path: "/"
      caBundle: --CA_BUNDLE--
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["networking.k8s.io"]
        apiVersions: ["v1beta1"]
        resources: ["ingress"]
    failurePolicy: Ignore
