replicas: 2

image:
  name: docker-registry.tools.wmflabs.org/ingress-admission
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: 50Mi
    cpu: 300m
  requests:
    memory: 50Mi
    cpu: 300m

webhook:
  secretName: ingress-admission-certs
  excludeNamespaces: ["tool-fourohfour"]
  failurePolicy: Fail

debug: false
domains:
  - toolforge.org
